name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test -- --run

      - name: i18n audit
        run: npm run i18n:audit

      - name: Build
        run: npm run build

      - name: Preview
        run: npm run preview -- --host 0.0.0.0 --port 4173 &

      - name: Wait for preview
        run: npx wait-on http://127.0.0.1:4173

      - name: Lighthouse CI
        run: npm run ci:lighthouse

      - name: Playwright install
        run: npx playwright install --with-deps

      - name: Playwright e2e
        run: npm run e2e

      - name: Stop preview
        run: kill $(jobs -p)
        if: always()

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse
          path: .lighthouse

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
